apiVersion: v1
kind: Service
metadata:
    name: auth-server
spec:
    selector:
        # This app must match the label of the pods.
        app: auth-server
    ports:
        - protocol: TCP
          port: 3300
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-server
spec:
    selector:
        matchLabels:
            # This is the label the app selector has to match.
            app: auth-server
    replicas: 1
    template:
        metadata:
            annotations:
                sidecar.istio.io/inject: 'false'
            labels:
                app: auth-server
        spec:
            containers:
                - name: auth-server
                  image: IMAGE_IS_INSERTED_USING_GITLAB-auth-server
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3300
                  resources:
                      # Requests are used to define the amount of resources the container minimally needs.
                      # It won’t run if it can not get those resources.
                      requests:
                          # 10m means 10 milli CPU and it is the same as 10/1000 of a CPU core or 1% of a CPU core
                          cpu: '10m'
                          # 16Mi means 16 mebibyte which corresponds to 16*1024² bytes.
                          memory: '16Mi'
                      # Limits are used to define the maximum of resources the container is allowed to use.
                      limits:
                          # This means that the container is maximum allowed to use 10% of a CPU core.
                          cpu: '100m'
                          # The same concepts as requests. This means the container is maximum allowed to use 128Mi memory.
                          # If the container uses more than the limit, it will get removed.
                          memory: '128Mi'
            imagePullSecrets:
                - name: sdugitlab
---
apiVersion: v1
kind: Service
metadata:
    name: gmail-server
spec:
    selector:
        # This app must match the label of the pods.
        app: gmail-server
    ports:
        - protocol: TCP
          port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gmail-server
spec:
    selector:
        matchLabels:
            # This is the label the app selector has to match.
            app: gmail-server
    replicas: 1
    template:
        metadata:
            annotations:
                sidecar.istio.io/inject: 'false'
            labels:
                app: gmail-server
        spec:
            containers:
                - name: gmail-server
                  image: IMAGE_IS_INSERTED_USING_GITLAB-gmail-server
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8081
                  resources:
                      # Requests are used to define the amount of resources the container minimally needs.
                      # It won’t run if it can not get those resources.
                      requests:
                          # 10m means 10 milli CPU and it is the same as 10/1000 of a CPU core or 1% of a CPU core
                          cpu: '10m'
                          # 16Mi means 16 mebibyte which corresponds to 16*1024² bytes.
                          memory: '16Mi'
                      # Limits are used to define the maximum of resources the container is allowed to use.
                      limits:
                          # This means that the container is maximum allowed to use 10% of a CPU core.
                          cpu: '100m'
                          # The same concepts as requests. This means the container is maximum allowed to use 128Mi memory.
                          # If the container uses more than the limit, it will get removed.
                          memory: '128Mi'
            imagePullSecrets:
                - name: sdugitlab
