apiVersion: v1
kind: Service
metadata:
    name: auth-server
spec:
    selector:
        # This app must match the label of the pods.
        app: auth-server
    ports:
        - protocol: TCP
          port: 3300
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-server
spec:
    selector:
        matchLabels:
            # This is the label the app selector has to match.
            app: auth-server
    replicas: 1
    template:
        metadata:
            annotations:
                sidecar.istio.io/inject: 'false'
            labels:
                app: auth-server
        spec:
            containers:
                - name: auth-server
                  image: IMAGE_IS_INSERTED_USING_GITLAB-auth-server
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3300
            imagePullSecrets:
                - name: sdugitlab
---
apiVersion: v1
kind: Service
metadata:
    name: gmail-server
spec:
    selector:
        # This app must match the label of the pods.
        app: gmail-server
    ports:
        - protocol: TCP
          port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gmail-server
spec:
    selector:
        matchLabels:
            # This is the label the app selector has to match.
            app: gmail-server
    replicas: 1
    template:
        metadata:
            annotations:
                sidecar.istio.io/inject: 'false'
            labels:
                app: gmail-server
        spec:
            containers:
                - name: gmail-server
                  image: IMAGE_IS_INSERTED_USING_GITLAB-gmail-server
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8081
            imagePullSecrets:
                - name: sdugitlab
