apiVersion: v1
kind: Service
metadata:
    name: service01
spec:
    selector:
        # This app must match the label of the pods.
        app: auth-server
    ports:
        - protocol: TCP
          port: 3300
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-server
spec:
    selector:
        matchLabels:
            # This is the label the app selector has to match.
            app: auth-server
    replicas: 1
    template:
        metadata:
            annotations:
            labels:
                app: auth-server
        spec:
            containers:
                - name: auth-server
                  image: IMAGE_IS_INSERTED_USING_GITLAB-auth-server
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3300
                  resources:
                      # Requests are used to define the amount of resources the container minimally needs.
                      # It won’t run if it can not get those resources.
                      requests:
                          # 10m means 10 milli CPU and it is the same as 10/1000 of a CPU core or 1% of a CPU core
                          cpu: '10m'
                          # 16Mi means 16 mebibyte which corresponds to 16*1024² bytes.
                          memory: '16Mi'
                      # Limits are used to define the maximum of resources the container is allowed to use.
                      limits:
                          # This means that the container is maximum allowed to use 10% of a CPU core.
                          cpu: '100m'
                          # The same concepts as requests. This means the container is maximum allowed to use 128Mi memory.
                          # If the container uses more than the limit, it will get removed.
                          memory: '128Mi'
            imagePullSecrets:
                - name: sdugitlab
---
apiVersion: v1
kind: Service
metadata:
    name: service02
spec:
    selector:
        # This app must match the label of the pods.
        app: gmail-server
    ports:
        - protocol: TCP
          port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gmail-server
spec:
    selector:
        matchLabels:
            # This is the label the app selector has to match.
            app: gmail-server
    replicas: 1
    template:
        metadata:
            annotations:
            labels:
                app: gmail-server
        spec:
            containers:
                - name: gmail-server
                  image: IMAGE_IS_INSERTED_USING_GITLAB-gmail-server
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8081
                  resources:
                      # Requests are used to define the amount of resources the container minimally needs.
                      # It won’t run if it can not get those resources.
                      requests:
                          # 10m means 10 milli CPU and it is the same as 10/1000 of a CPU core or 1% of a CPU core
                          cpu: '10m'
                          # 16Mi means 16 mebibyte which corresponds to 16*1024² bytes.
                          memory: '16Mi'
                      # Limits are used to define the maximum of resources the container is allowed to use.
                      limits:
                          # This means that the container is maximum allowed to use 10% of a CPU core.
                          cpu: '100m'
                          # The same concepts as requests. This means the container is maximum allowed to use 128Mi memory.
                          # If the container uses more than the limit, it will get removed.
                          memory: '128Mi'
            imagePullSecrets:
                - name: sdugitlab
---
apiVersion: v1
kind: Service
metadata:
    name: service03
spec:
    selector:
        # This app must match the label of the pods.
        app: frontend
    ports:
        - protocol: TCP
          port: 3031
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
spec:
    selector:
        matchLabels:
            # This is the label the app selector has to match.
            app: frontend
    replicas: 1
    template:
        metadata:
            annotations:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: gitlab.sdu.dk:5050/semester-project-e2020/team-10-connection-security/template:frontend
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3301
                  resources:
                      # Requests are used to define the amount of resources the container minimally needs.
                      # It won’t run if it can not get those resources.
                      requests:
                          # 10m means 10 milli CPU and it is the same as 10/1000 of a CPU core or 1% of a CPU core
                          cpu: '10m'
                          # 16Mi means 16 mebibyte which corresponds to 16*1024² bytes.
                          memory: '16Mi'
                      # Limits are used to define the maximum of resources the container is allowed to use.
                      limits:
                          # This means that the container is maximum allowed to use 10% of a CPU core.
                          cpu: '100m'
                          # The same concepts as requests. This means the container is maximum allowed to use 128Mi memory.
                          # If the container uses more than the limit, it will get removed.
                          memory: '128Mi'
            imagePullSecrets:
                - name: sdugitlab
---

---
apiVersion: v1
kind: Service
metadata:
    name: service04
spec:
    selector:
        # This app must match the label of the pods.
        app: userapi
    ports:
        - protocol: TCP
          port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: userapi
spec:
    selector:
        matchLabels:
            # This is the label the app selector has to match.
            app: userapi
    replicas: 1
    template:
        metadata:
            annotations:
            labels:
                app: userapi
        spec:
            containers:
                - name: userapi
                  image: gitlab.sdu.dk:5050/semester-project-e2020/team-10-connection-security/template:userapi
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 9090
                  resources:
                      # Requests are used to define the amount of resources the container minimally needs.
                      # It won’t run if it can not get those resources.
                      requests:
                          # 10m means 10 milli CPU and it is the same as 10/1000 of a CPU core or 1% of a CPU core
                          cpu: '10m'
                          # 16Mi means 16 mebibyte which corresponds to 16*1024² bytes.
                          memory: '16Mi'
                      # Limits are used to define the maximum of resources the container is allowed to use.
                      limits:
                          # This means that the container is maximum allowed to use 10% of a CPU core.
                          cpu: '100m'
                          # The same concepts as requests. This means the container is maximum allowed to use 128Mi memory.
                          # If the container uses more than the limit, it will get removed.
                          memory: '128Mi'
            imagePullSecrets:
                - name: sdugitlab
---

