version: '3'
services:
    nginx:
        build:
            context: ./reverse_proxy/
            #dockerfile: dockerfileNameOfNginxDockerFile_Not_necersary
            args:
                buildno: 1
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./reverse_proxy/cert_key/:/etc/nginx/certs
            - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./html/:/usr/share/nginx/html/
        networks:
            - frontEndNetwork

    authservice:
        build:
            context: ./authServer/
            #dockerfile: dockerfileNameOfNginxDockerFile_Not_necersary
            args:
                buildno: 1
        expose:
            - '3300'
        networks:
            - frontEndNetwork
            - backEndNetwork

    gmailservice:
        build:
            context: ./gmailserver/
            #dockerfile: dockerfileNameOfNginxDockerFile_Not_necersary
            args:
                buildno: 1
        expose:
            - '8081'
        networks:
            - frontEndNetwork
            - backEndNetwork

    userapiservice:
        build:
            context: ./userAPI/
            #dockerfile: dockerfileNameOfNginxDockerFile_Not_necersary
            args:
                buildno: 1
        expose:
            - '8082'
        networks:
            - backEndNetwork

networks:
    frontEndNetwork:
    backEndNetwork:
