# Generated by Django 3.2.9 on 2021-11-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('audio_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('JSON', models.JSONField(blank=True, null=True)),
                ('artfile', models.FileField(null=True, upload_to='')),
                ('audiofile', models.FileField(upload_to='temp')),
            ],
        ),
        migrations.CreateModel(
            name='AudioObject',
            fields=[
                ('audio_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('JSON', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
