version: "3.3"

services:
  db:
    build: ./Docker/

  web:
    build: .
    command: >
      sh -c "python3 manage.py wait_for_database &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    links:
      - "db:database"
    ports:
      - "8000:8000"
    depends_on:
      - db


